/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchRouteImport } from './routes/watch'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayOnlineRouteImport } from './routes/play-online'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PassRouteImport } from './routes/pass'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as FoodRouteImport } from './routes/food'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoviesSeatsRouteImport } from './routes/movies.seats'
import { Route as MoviesCheckoutRouteImport } from './routes/movies.checkout'
import { Route as MoviesBookSeatRouteImport } from './routes/movies.book-seat'
import { Route as GamingPassRouteImport } from './routes/gaming.pass'
import { Route as GamingCheckoutRouteImport } from './routes/gaming.checkout'
import { Route as GamingBookingRouteImport } from './routes/gaming.booking'
import { Route as EventsTournamentsRouteImport } from './routes/events.tournaments'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthVerifyRouteImport } from './routes/auth.verify'
import { Route as AuthUniversityLoginRouteImport } from './routes/auth.university-login'
import { Route as AuthSuccessRouteImport } from './routes/auth.success'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthGuestLoginRouteImport } from './routes/auth.guest-login'

const WatchRoute = WatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayOnlineRoute = PlayOnlineRouteImport.update({
  id: '/play-online',
  path: '/play-online',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PassRoute = PassRouteImport.update({
  id: '/pass',
  path: '/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesSeatsRoute = MoviesSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => MoviesRoute,
} as any)
const MoviesCheckoutRoute = MoviesCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MoviesRoute,
} as any)
const MoviesBookSeatRoute = MoviesBookSeatRouteImport.update({
  id: '/book-seat',
  path: '/book-seat',
  getParentRoute: () => MoviesRoute,
} as any)
const GamingPassRoute = GamingPassRouteImport.update({
  id: '/gaming/pass',
  path: '/gaming/pass',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingCheckoutRoute = GamingCheckoutRouteImport.update({
  id: '/gaming/checkout',
  path: '/gaming/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const GamingBookingRoute = GamingBookingRouteImport.update({
  id: '/gaming/booking',
  path: '/gaming/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsTournamentsRoute = EventsTournamentsRouteImport.update({
  id: '/events/tournaments',
  path: '/events/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyRoute = AuthVerifyRouteImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUniversityLoginRoute = AuthUniversityLoginRouteImport.update({
  id: '/auth/university-login',
  path: '/auth/university-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuestLoginRoute = AuthGuestLoginRouteImport.update({
  id: '/auth/guest-login',
  path: '/auth/guest-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/food': typeof FoodRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRouteWithChildren
  '/pass': typeof PassRoute
  '/payment': typeof PaymentRoute
  '/play-online': typeof PlayOnlineRoute
  '/profile': typeof ProfileRoute
  '/receipt': typeof ReceiptRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/auth/guest-login': typeof AuthGuestLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/university-login': typeof AuthUniversityLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/events/tournaments': typeof EventsTournamentsRoute
  '/gaming/booking': typeof GamingBookingRoute
  '/gaming/checkout': typeof GamingCheckoutRoute
  '/gaming/pass': typeof GamingPassRoute
  '/movies/book-seat': typeof MoviesBookSeatRoute
  '/movies/checkout': typeof MoviesCheckoutRoute
  '/movies/seats': typeof MoviesSeatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/food': typeof FoodRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRouteWithChildren
  '/pass': typeof PassRoute
  '/payment': typeof PaymentRoute
  '/play-online': typeof PlayOnlineRoute
  '/profile': typeof ProfileRoute
  '/receipt': typeof ReceiptRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/auth/guest-login': typeof AuthGuestLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/university-login': typeof AuthUniversityLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/events/tournaments': typeof EventsTournamentsRoute
  '/gaming/booking': typeof GamingBookingRoute
  '/gaming/checkout': typeof GamingCheckoutRoute
  '/gaming/pass': typeof GamingPassRoute
  '/movies/book-seat': typeof MoviesBookSeatRoute
  '/movies/checkout': typeof MoviesCheckoutRoute
  '/movies/seats': typeof MoviesSeatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/booking': typeof BookingRoute
  '/food': typeof FoodRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/movies': typeof MoviesRouteWithChildren
  '/pass': typeof PassRoute
  '/payment': typeof PaymentRoute
  '/play-online': typeof PlayOnlineRoute
  '/profile': typeof ProfileRoute
  '/receipt': typeof ReceiptRoute
  '/rewards': typeof RewardsRoute
  '/support': typeof SupportRoute
  '/watch': typeof WatchRoute
  '/auth/guest-login': typeof AuthGuestLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/university-login': typeof AuthUniversityLoginRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
  '/events/tournaments': typeof EventsTournamentsRoute
  '/gaming/booking': typeof GamingBookingRoute
  '/gaming/checkout': typeof GamingCheckoutRoute
  '/gaming/pass': typeof GamingPassRoute
  '/movies/book-seat': typeof MoviesBookSeatRoute
  '/movies/checkout': typeof MoviesCheckoutRoute
  '/movies/seats': typeof MoviesSeatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/booking'
    | '/food'
    | '/leaderboard'
    | '/login'
    | '/movies'
    | '/pass'
    | '/payment'
    | '/play-online'
    | '/profile'
    | '/receipt'
    | '/rewards'
    | '/support'
    | '/watch'
    | '/auth/guest-login'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/success'
    | '/auth/university-login'
    | '/auth/verify'
    | '/auth/verify-otp'
    | '/events/tournaments'
    | '/gaming/booking'
    | '/gaming/checkout'
    | '/gaming/pass'
    | '/movies/book-seat'
    | '/movies/checkout'
    | '/movies/seats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/booking'
    | '/food'
    | '/leaderboard'
    | '/login'
    | '/movies'
    | '/pass'
    | '/payment'
    | '/play-online'
    | '/profile'
    | '/receipt'
    | '/rewards'
    | '/support'
    | '/watch'
    | '/auth/guest-login'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/success'
    | '/auth/university-login'
    | '/auth/verify'
    | '/auth/verify-otp'
    | '/events/tournaments'
    | '/gaming/booking'
    | '/gaming/checkout'
    | '/gaming/pass'
    | '/movies/book-seat'
    | '/movies/checkout'
    | '/movies/seats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/booking'
    | '/food'
    | '/leaderboard'
    | '/login'
    | '/movies'
    | '/pass'
    | '/payment'
    | '/play-online'
    | '/profile'
    | '/receipt'
    | '/rewards'
    | '/support'
    | '/watch'
    | '/auth/guest-login'
    | '/auth/login'
    | '/auth/signup'
    | '/auth/success'
    | '/auth/university-login'
    | '/auth/verify'
    | '/auth/verify-otp'
    | '/events/tournaments'
    | '/gaming/booking'
    | '/gaming/checkout'
    | '/gaming/pass'
    | '/movies/book-seat'
    | '/movies/checkout'
    | '/movies/seats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookingRoute: typeof BookingRoute
  FoodRoute: typeof FoodRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MoviesRoute: typeof MoviesRouteWithChildren
  PassRoute: typeof PassRoute
  PaymentRoute: typeof PaymentRoute
  PlayOnlineRoute: typeof PlayOnlineRoute
  ProfileRoute: typeof ProfileRoute
  ReceiptRoute: typeof ReceiptRoute
  RewardsRoute: typeof RewardsRoute
  SupportRoute: typeof SupportRoute
  WatchRoute: typeof WatchRoute
  AuthGuestLoginRoute: typeof AuthGuestLoginRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthUniversityLoginRoute: typeof AuthUniversityLoginRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  EventsTournamentsRoute: typeof EventsTournamentsRoute
  GamingBookingRoute: typeof GamingBookingRoute
  GamingCheckoutRoute: typeof GamingCheckoutRoute
  GamingPassRoute: typeof GamingPassRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watch': {
      id: '/watch'
      path: '/watch'
      fullPath: '/watch'
      preLoaderRoute: typeof WatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play-online': {
      id: '/play-online'
      path: '/play-online'
      fullPath: '/play-online'
      preLoaderRoute: typeof PlayOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pass': {
      id: '/pass'
      path: '/pass'
      fullPath: '/pass'
      preLoaderRoute: typeof PassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/seats': {
      id: '/movies/seats'
      path: '/seats'
      fullPath: '/movies/seats'
      preLoaderRoute: typeof MoviesSeatsRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/movies/checkout': {
      id: '/movies/checkout'
      path: '/checkout'
      fullPath: '/movies/checkout'
      preLoaderRoute: typeof MoviesCheckoutRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/movies/book-seat': {
      id: '/movies/book-seat'
      path: '/book-seat'
      fullPath: '/movies/book-seat'
      preLoaderRoute: typeof MoviesBookSeatRouteImport
      parentRoute: typeof MoviesRoute
    }
    '/gaming/pass': {
      id: '/gaming/pass'
      path: '/gaming/pass'
      fullPath: '/gaming/pass'
      preLoaderRoute: typeof GamingPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming/checkout': {
      id: '/gaming/checkout'
      path: '/gaming/checkout'
      fullPath: '/gaming/checkout'
      preLoaderRoute: typeof GamingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaming/booking': {
      id: '/gaming/booking'
      path: '/gaming/booking'
      fullPath: '/gaming/booking'
      preLoaderRoute: typeof GamingBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/tournaments': {
      id: '/events/tournaments'
      path: '/events/tournaments'
      fullPath: '/events/tournaments'
      preLoaderRoute: typeof EventsTournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/university-login': {
      id: '/auth/university-login'
      path: '/auth/university-login'
      fullPath: '/auth/university-login'
      preLoaderRoute: typeof AuthUniversityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/guest-login': {
      id: '/auth/guest-login'
      path: '/auth/guest-login'
      fullPath: '/auth/guest-login'
      preLoaderRoute: typeof AuthGuestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MoviesRouteChildren {
  MoviesBookSeatRoute: typeof MoviesBookSeatRoute
  MoviesCheckoutRoute: typeof MoviesCheckoutRoute
  MoviesSeatsRoute: typeof MoviesSeatsRoute
}

const MoviesRouteChildren: MoviesRouteChildren = {
  MoviesBookSeatRoute: MoviesBookSeatRoute,
  MoviesCheckoutRoute: MoviesCheckoutRoute,
  MoviesSeatsRoute: MoviesSeatsRoute,
}

const MoviesRouteWithChildren =
  MoviesRoute._addFileChildren(MoviesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookingRoute: BookingRoute,
  FoodRoute: FoodRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MoviesRoute: MoviesRouteWithChildren,
  PassRoute: PassRoute,
  PaymentRoute: PaymentRoute,
  PlayOnlineRoute: PlayOnlineRoute,
  ProfileRoute: ProfileRoute,
  ReceiptRoute: ReceiptRoute,
  RewardsRoute: RewardsRoute,
  SupportRoute: SupportRoute,
  WatchRoute: WatchRoute,
  AuthGuestLoginRoute: AuthGuestLoginRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthUniversityLoginRoute: AuthUniversityLoginRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  EventsTournamentsRoute: EventsTournamentsRoute,
  GamingBookingRoute: GamingBookingRoute,
  GamingCheckoutRoute: GamingCheckoutRoute,
  GamingPassRoute: GamingPassRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
