/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyOtpRouteImport } from './routes/auth.verify-otp'
import { Route as AuthUniversityLoginRouteImport } from './routes/auth.university-login'
import { Route as AuthSuccessRouteImport } from './routes/auth.success'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthGuestLoginRouteImport } from './routes/auth.guest-login'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/auth/verify-otp',
  path: '/auth/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUniversityLoginRoute = AuthUniversityLoginRouteImport.update({
  id: '/auth/university-login',
  path: '/auth/university-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSuccessRoute = AuthSuccessRouteImport.update({
  id: '/auth/success',
  path: '/auth/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGuestLoginRoute = AuthGuestLoginRouteImport.update({
  id: '/auth/guest-login',
  path: '/auth/guest-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/guest-login': typeof AuthGuestLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/university-login': typeof AuthUniversityLoginRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/guest-login': typeof AuthGuestLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/university-login': typeof AuthUniversityLoginRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auth/guest-login': typeof AuthGuestLoginRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/success': typeof AuthSuccessRoute
  '/auth/university-login': typeof AuthUniversityLoginRoute
  '/auth/verify-otp': typeof AuthVerifyOtpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auth/guest-login'
    | '/auth/login'
    | '/auth/success'
    | '/auth/university-login'
    | '/auth/verify-otp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auth/guest-login'
    | '/auth/login'
    | '/auth/success'
    | '/auth/university-login'
    | '/auth/verify-otp'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/auth/guest-login'
    | '/auth/login'
    | '/auth/success'
    | '/auth/university-login'
    | '/auth/verify-otp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AuthGuestLoginRoute: typeof AuthGuestLoginRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSuccessRoute: typeof AuthSuccessRoute
  AuthUniversityLoginRoute: typeof AuthUniversityLoginRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-otp': {
      id: '/auth/verify-otp'
      path: '/auth/verify-otp'
      fullPath: '/auth/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/university-login': {
      id: '/auth/university-login'
      path: '/auth/university-login'
      fullPath: '/auth/university-login'
      preLoaderRoute: typeof AuthUniversityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/success': {
      id: '/auth/success'
      path: '/auth/success'
      fullPath: '/auth/success'
      preLoaderRoute: typeof AuthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/guest-login': {
      id: '/auth/guest-login'
      path: '/auth/guest-login'
      fullPath: '/auth/guest-login'
      preLoaderRoute: typeof AuthGuestLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AuthGuestLoginRoute: AuthGuestLoginRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSuccessRoute: AuthSuccessRoute,
  AuthUniversityLoginRoute: AuthUniversityLoginRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
